##### Import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from langdetect import detect
from langdetect.lang_detect_exception import LangDetectException
import re
import spacy
import nltk
from nltk.corpus import stopwords
import plotly.express as px

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\balog\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\balog\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

##### Load the dataset

In [2]:
df_clean = pd.read_csv(r'C:\Users\balog\OneDrive\Documents\Olayemi\Intership\Customer Feedback Analysis\Data\cleaned_amazon_reviews.csv')

##### Dashboard Reporting Tables

- Category Summary

In [5]:
category_summary = (
    df_clean.groupby("product_category").agg(Total_Reviews=("review_id","count"),Average_Rating=("rating","mean")).reset_index())

category_summary

  product_category  Total_Reviews  Average_Rating
0           Beauty           2866        2.146895
1      Electronics           2895        2.144041
2          Fashion           2883        2.223032
3   Food & Grocery           2841        2.128476
4    Home & Living           2988        2.090027
5           Sports           3060        2.177778
6             Toys           2872        2.101671

In [7]:
category_summary.to_excel("category_summary.xlsx", index=False)

- Sentiment Summary

In [11]:
sentiment_summary = (df_clean.groupby(["product_category","sentiment"]) .size().reset_index(name="total_reviews"))
sentiment_summary

   product_category sentiment  total_reviews
0            Beauty  Negative           1973
1            Beauty   Neutral            130
2            Beauty  Positive            763
3       Electronics  Negative           2016
4       Electronics   Neutral            114
5       Electronics  Positive            765
6           Fashion  Negative           1935
7           Fashion   Neutral            125
8           Fashion  Positive            823
9    Food & Grocery  Negative           1977
10   Food & Grocery   Neutral            118
11   Food & Grocery  Positive            746
12    Home & Living  Negative           2128
13    Home & Living   Neutral            108
14    Home & Living  Positive            752
15           Sports  Negative           2101
16           Sports   Neutral            109
17           Sports  Positive            850
18             Toys  Negative           2026
19             Toys   Neutral            121
20             Toys  Positive            725

In [12]:
sentiment_summary.to_excel("sentiment_summary.xlsx", index=False)

- Country Summary

In [13]:
country_summary = (df_clean.groupby("country").agg(Total_Reviews=("review_id","count"), Average_Rating=("rating","mean")).reset_index())
country_summary

    country  Total_Reviews  Average_Rating
0        AD              2        5.000000
1        AE             82        1.914634
2        AF              1        1.000000
3        AG              1        1.000000
4        AM              9        2.000000
..      ...            ...             ...
140      VG              1        3.000000
141      VI              1        1.000000
142      VN             16        2.562500
143      ZA             51        1.568627
144      ZM              1        5.000000

[145 rows x 3 columns]

In [14]:
country_summary.to_excel("country_summary.xlsx", index=False)